Pass GitHub token to GitHub API when fetching grcov release info
Address a build flake that looks like this:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   280  100   280    0     0   2944      0 --:--:-- --:--:-- --:--:--  2916
jq: error (at <stdin>:1): Cannot index object with number
Error: Process completed with exit code 5.
```

See for example: https://github.com/artichoke/roe/actions/runs/3815322171/jobs/6490232071

To attempt a fix:

- Set the content type to the more modern application/json.
- Pass `secrets.GITHUB_TOKEN` as a bearer token in the `Authorization`
  header.
- Use `--silent` and `--fail` to prevent curl from echoing outputs in
  the subshell pipeline.
- Add 3 retries to the curl call.

This commit also breaks up the `jq` expression over multiple lines for
readability.